export const MOVIES_LOADING = 'MOVIES_LOADED';
export const MOVIES_LOADED = 'END_MOVIES_LOADING';
export const SELECTED_MOVIE_LOADING = 'SELECTED_MOVIE_LOADING';
export const SELECTED_MOVIE_LOADED = 'SELECTED_MOVIE_LOADED';

export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_SELECTED_MOVIE = 'LOAD_SELECTED_MOVIE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
