// app reducer
export const START_MOVIES_LOADING = 'START_MOVIES_LOADING';
export const END_MOVIES_LOADING = 'END_MOVIES_LOADING';
export const START_SELECTED_MOVIE_LOADING = 'START_SELECTED_MOVIE_LOADING';
export const END_SELECTED_MOVIE_LOADING = 'END_SELECTED_MOVIE_LOADING';

// movies reducer
export const LOADED_MOVIES = 'LOADED_MOVIES';
export const LOADED_SELECTED_MOVIE = 'LOADED_SELECTED_MOVIE';
